name: application
description: Nebrass Mobile Application
version: 1.0.0+1

  #https://pub.dev/packages/simple_coverflow
  #simple_coverflow: ^0.0.8
  #image_ink_well: ^0.1.0
  #https://github.com/acadia3000/image_ink_well
  #chopper: ^3.0.2
  #flutter_bloc: ^3.2.0
  #equatable: ^1.1.1
  #sliding_up_panel: ^1.0.1
  #bubble_tab_indicator: ^0.1.4
  #hermes: ^3.0.0
  #bubble_tab_indicator: "^0.1.4"
  #https://github.com/JordanADavies/liquid_progress_indicator
  #event_bus: ^1.1.1
  #polygon_clipper: ^1.0.2
  #rect_getter: ^0.1.0
#flutter_parsed_text: ^1.2.1
environment:
  sdk: '>=2.8.0-dev.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  photo_view: ^0.9.2
  md2_tab_indicator: ^1.0.2
  drag_select_grid_view: ^0.2.0
  watcher: ^0.9.7+15
  get_it: ^4.0.2
  flutter_fps: ^0.0.2
  states_rebuilder: ^1.15.0
  rxdart: ^0.24.0
  animator: ^1.0.0+5
  cached_network_image: ^2.2.0
  shared_preferences: ^0.5.7
  json_annotation: ^3.0.1
  http: ^0.12.1
  email_validator: ^1.0.4
  badges: ^1.1.1
  esys_flutter_share: ^1.0.2
  camera: ^0.5.7+4
  avatar_glow: ^1.1.0
  circular_profile_avatar: ^1.0.6
  overlay_support: ^1.0.3
  grouped_buttons: ^1.0.4
  animated_theme_switcher: ^1.0.6
  permission_handler: ^5.0.0+hotfix.4
  icon_shadow: ^1.0.1
  fl_chart: ^0.10.1
  ffcache: ^0.1.3
  path_provider: ^1.6.7
  url_launcher: ^5.4.5
  font_awesome_flutter: ^8.8.1
  circular_reveal_animation: ^1.1.5
  animations: ^1.0.0+5
  streaming_shared_preferences: ^1.0.1
  provider: ^4.0.5+1
  flutter_hooks: ^0.9.0
  flutter_statusbarcolor: any
  chewie: ^0.9.10
  video_player: ^0.10.9+1
  #hive: ^1.4.1+1
  #hive_flutter: ^0.3.0+2
  expandable_bottom_bar: ^1.0.2
  fab_circular_menu: ^1.0.0
  carousel_slider: ^1.4.1
  flutter_crashlytics: ^1.0.0
  logging: ^0.11.4
  connectivity: ^0.4.8+2
  built_value: ^7.1.0
  flutter_spinkit: ^4.1.2+1
  oktoast: ^2.3.2
  flutter_html: ^0.11.1
  auto_animated: ^2.0.2
  sailor: ^0.7.1
  flutter_staggered_grid_view: ^0.3.0
  rubber: ^0.4.0
  flutter_parsed_text: ^1.2.4
  scrollable_positioned_list: ^0.1.5
  storage_path: ^0.2.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  #chopper_generator: ^3.0.4
  built_value_generator: ^7.1.0
  #hive_generator: ^0.7.0+2
  lint: ^1.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/iran_yekan.ttf
    - family: iranSansLight
      fonts:
        - asset: assets/fonts/iran_sans_light.ttf
    - family: iranSansBold
      fonts:
        - asset: assets/fonts/iran_sans_bold.ttf
    - family: consolas
      fonts:
        - asset: assets/fonts/consola.ttf
    - family: beautifulLovers
      fonts:
        - asset: assets/fonts/beautiful_lovers.ttf
    - family: beautifulPeople
      fonts:
        - asset: assets/fonts/beautiful_people.ttf
    - family: ShabnamLight
      fonts:
        - asset: assets/fonts/shabnam.ttf
    - family: ShabnamBold
      fonts:
        - asset: assets/fonts/shabnam_bold.ttf
    - family: Baridya
      fonts:
        - asset: assets/fonts/bardiya.ttf
    - family: BardiyaBold
      fonts:
        - asset: assets/fonts/bardiya_bold.ttf
    - family: Ghasem
      fonts:
        - asset: assets/fonts/ghasem.ttf

  #https://github.com/Milad-Akarie/smooth_page_indicator
  #https://github.com/Milad-Akarie/form_field_validator
  #https://github.com/Milad-Akarie/pretty_dio_logger
  #https://pub.dev/packages/flutter_swiper
  #https://medium.com/@bimsina/animated-icons-in-flutter-3ca7e921500a
  #https://github.com/neumorphic/neumorphic.flutter
  #FadeInImage (Flutter Widget of the Week)
  #https://pub.dev/packages/loading_animations
  #https://pub.dev/packages/persian_number_utility
  #https://pub.dev/packages/auto_animated
  #
  #
  #
  #
  #
  #flutter build --verbose
  #flutter build --verbose aar
  #flutter build --verbose apk
  #flutter clean
  #flutter pub cache repair
  #flutter build apk --target-platform android-arm,android-arm64
  #sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
  #sudo xcodebuild -license